/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "pages/index/index" |
       "pages/calendar/index" |
       "pages/category/index" |
       "pages/divinatory-symbol/Detail" |
       "pages/divinatory-symbol/List" |
       "pages/history/index" |
       "pages/setting/index" |
       "pages-other/category/index" |
       "pages-other/divinatory-symbol/Detail";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void
}
